import './globals.css'
import Navbar from './components/Navbar'
import { font } from './fonts'

export const metadata = {
  title: 'Next 13',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={font.className}>
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
